# ArgoCD ApplicationをManifestで作成する際に使用する。
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rafty/handson-eks_app_manifest.git
    targetRevision: HEAD
    path: flask/dev/
  destination:
    server: https://4A44592A7DAC736CC7587E9CCEC7DA3C.gr7.ap-northeast-1.eks.amazonaws.com
    namespace: flask-app
  syncPolicy:
    automated: {}
