apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rafty/eks-gitops-app-manifest.git
    targetRevision: HEAD
    path: flask_workshop/frontend/dev/
  destination:
    server: https://4A44592A7DAC736CC7587E9CCEC7DA3C.gr7.ap-northeast-1.eks.amazonaws.com
    namespace: flask-frontend
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rafty/eks-gitops-app-manifest.git
    targetRevision: HEAD
    path: flask_workshop/backend/dev/
  destination:
    server: https://4A44592A7DAC736CC7587E9CCEC7DA3C.gr7.ap-northeast-1.eks.amazonaws.com
    namespace: flask-backend
  syncPolicy:
    automated: {}
#    syncOptions:
#    - CreateNamespace=true  # namespaceはcdkで作成
